project:
  type: website
  output-dir: docs

website:
  title: "My Example Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Assignments"
        menu:
          - ae03-gerrymander.qmd
    right:
      - icon: github
        href: https://github.com/rawenslaff

format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true



